export const foods = [
  {
    id: 1,
    title: "Porkchop with Garlic Sauce",
    price: "100",
    category: "Main Course",
    description: "Aroma of garlic and spices, with a hint of sweetness.",
    image: "/assets/foods/main/porkchop-with-garlic-sauce.jpg",
  },
  {
    id: 2,
    title: "Salmon Steak with Tartar Sauce",
    price: "150",
    category: "Main Course",
    description: "Crumbly and juicy salmon, with a hint of sweetness.",
    image: "/assets/foods/main/salmon-steak-with-tartar-sauce.jpg",
  },
  {
    id: 3,
    title: "Creamy Noodle Soup",
    price: "80",
    category: "Main Course",
    description: "Creamy soup with noodles, vegetables, and meat.",
    image: "/assets/foods/main/creamy-noodle-soup.jpg",
  },
  {
    id: 4,
    title: "Chicken Curry",
    price: "120",
    category: "Main Course",
    description: "Curry with chicken, vegetables, and spices.",
    image: "/assets/foods/main/chicken-curry.jpg",
  },
  {
    id: 5,
    title: "Japanese Beef Curry",
    price: "150",
    category: "Main Course",
    description: "Japanese style beef curry with vegetables.",
    image: "/assets/foods/main/beef-curry.jpg",
  },
  {
    id: 6,
    title: "Cheese Cake",
    price: "80",
    category: "Dessert",
    description: "Creamy cheese cake with a hint of sweetness.",
    image: "/assets/foods/dessert/cheese-cake.jpg",
  },
  {
    id: 7,
    title: "Chocolate Cake",
    price: "80",
    category: "Dessert",
    description: "Chocolate cake with a hint of sweetness.",
    image: "/assets/foods/dessert/chocolate-cake.jpg",
  },
  {
    id: 8,
    title: "Daifuku",
    price: "70",
    category: "Dessert",
    description: "Japanese sweets",
    image: "/assets/foods/dessert/daifuku.jpg",
  },
  {
    id: 9,
    title: "Ice Cream",
    price: "60",
    category: "Dessert",
    description: "Refreshing ice cream",
    image: "/assets/foods/dessert/ice-cream.jpg",
  },
  {
    id: 10,
    title: "Pancakes",
    price: "30",
    category: "Dessert",
    description: "Delicious pancakes",
    image: "/assets/foods/dessert/pancakes.jpg",
  },
  {
    id: 11,
    title: "Orange Smoothie",
    price: "40",
    category: "Drink",
    description: "Refreshing orange smoothie",
    image: "/assets/foods/drink/orange-smoothie.jpg",
  },
  {
    id: 12,
    title: "Strawberry Smoothie",
    price: "40",
    category: "Drink",
    description: "Refreshing strawberry smoothie",
    image: "/assets/foods/drink/strawberry-smoothie.jpg",
  },
  {
    id: 13,
    title: "Coffee",
    price: "30",
    category: "Drink",
    description: "Refreshing coffee",
    image: "/assets/foods/drink/coffee.jpg",
  },
];
